# site settings
title: Pain and Aversive System Resources
subtitle: by Pain and Aversive System Lab
email: ben.seymour@ndcn.ox.ac.uk
description: Presenting a series of tools and datasets for pain and aversive system research
baseurl: "/main" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Old Road Campus Building
city: Oxford
state: 
zip_code: OX3 7DQ
country: United Kingdom
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Pain-and-aversive-system
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
